#开关,当对应选项为true时则为启用这个功能,为false时则为禁用
#Sleep:睡眠 Thirst:饮水 PhysicalStrength:体力 Temperature:温度 Weight:负重 Sick:生病 Fracture:骨折
Switch:
  Sleep: true
  Thirst: true
  PhysicalStrength: true
  Temperature: true
  Weight: true
  Sick: true
  Fracture: true

#把你想要启用的世界填入下面
#格式:
#  - WorldName
Worlds:
  - world
  - world_nether
  - world_the_end

#玩家死亡重生时在现有的数值上恢复对应最大值的百分比(用小数表示)
#Sleep为在死亡时,剩余Sleep数值基础上增加睡眠值最大值的多少倍
#Thirst,PhysicalStrength同上
#IsSick为在死亡时是否清空生病信息(1为清空,0为不清空),Temperature为设定复活后温度(36-38温度为正常温度)
OnDeath:
  Sleep: 0.2
  Thirst: 0.2
  PhysicalStrength: 0.2
  Temperature: 37
  IsSick: 0
  
#Sleep一栏
#Max为睡眠饱和值 Mid为当前睡眠度为睡眠饱和值的0.x倍后感觉困意 Min为当前睡眠度为睡眠饱和值的0.x倍后感觉非常疲劳
#Sub为每1秒减多少睡眠值 Add为睡觉时每1秒增加多少睡眠值
#口渴值与睡眠值一个套路
Sleep:
  Max: 100
  Mid: 0.3
  Min: 0.15
  Sub: 0.05
  Add: 5
Thirst:
  Max: 100
  Mid: 0.5
  Min: 0.2
  Sub: 0.03
  
#骨折,
#Slight下面为轻微骨折,Severe为严重骨折,High代表从多高跳下来时触发,Chance代表触发几率
#Damage为被下落的方块砸到损失了多少血后触发骨折效果
#SlChance为被掉落方块砸到造成骨折的几率 SeChance为被掉落方块砸到造成严重骨折的几率
#几率不用加% 高度的话,假如骨折触发高度填的是6,实际触发高度是3+6=9格,也就是说从9格跳下来会骨折
Fracture:
  Slight:
    High: 3
    Chance: 20
  Severe:
    High: 6
    Chance: 80
  Damage: 2
  SlChance: 10
  SeChance: 30
  
#体力,
#Max为体力最大值,min为体力达到最大值的几倍后感到体力不支,Add为停止动作时每10秒增加多少体力,Sneaking潜行状态下每10秒减多少体力,Sprinting短跑状态下每10秒减多少体力
PhysicalStrength:
  Max: 100
  Min: 0.2
  Add: 2
  Sneaking: 1
  Sprinting: 2
  
#生病
#SickName代表默认情况下得到的病的种类, 生病种类必须在Effect下出现过,否则插件会报错
#EatFood为吃了哪种食物后有几率得指定的病
#添加格式: "- 食物名:疾病名,几率;疾病名2,几率2;...;疾病名n,几率n"
#食物名需要大写,可以通过游戏中/rs test open指令来获取指定食物名,";"为分隔符,通过这个符号可以添加多种疾病几率
Sick:
  SickName: 生病
  EatFood:
    - RAW_CHICKEN:生病,10%;感冒,10%
    
#食物名:睡眠度,口渴度,体温
#口渴度与睡眠度的值都为最大值的百分之几,可以是负数
EatFood:
  - APPLE:+1%,+5%,0
  - RAW_CHICKEN:+5%,-5%,0
  
#自定义高级工作台的摆放方式 Main为被右击的方块 left为左边 Right为右边 UP为上方 Down为下方 Front为前面 Behind为后面  写方块名的时候注意大写,并且当不需要那一边的话写上 Null 
#默认主方块是工作台 左边方块是书架 右边方块是工作台 上方是熔炉
Workbench:
  Title: Workbench
  Main: WORKBENCH
  Left: BOOKSHELF
  Right: WORKBENCH
  UP: FURNACE
  Down: Null
  Front: Null
  Behind: Null
  
#除了HeatSourceFix不一样,其他都和上面一样
#HeatSourceFix为温度修正,效果为热源对于工作台的温度是热源本身温度的xx倍,可以为小数
FireCraftTable:
  Title: FireCraftTable
  Main: FURNACE
  Left: BOOKSHELF
  Right: WORKBENCH
  UP: WORKBENCH
  Down: Null
  Front: Null
  Behind: Null
  HeatSourceFix: 100.0
  
#最大负重值
#Item下为默认物品重量,物品名大写,添加格式为:
#  - 物品名:重量
Weight:
  Max: 100
  Item:
  - TORCH:0.1
  
#热(冷)源 添加格式:
#  - 方块名:温度值
#方块名(物品名)大写
#DistanceEffect为热源离玩家距离衰减倍数
#假如一个热度为m的热源离你3格远,那么热源的温度最终为m(1-DistanceEffect)^3
HeatSource:
- DistanceEffect:0.25
- FIRE:0.3
- LAVA:0.5
- TORCH:0.1
- FLOWING_LAVA:0.5
- STATIONARY_LAVA:0.5
- LAVA_BUCKET:0.5
- WATER:-0.3
- FLOWING_WATER:-0.3
- PACKED_ICE:-0.3
- ICE:-0.3
- FROSTED_ICE:-0.3
- SNOW_LAYER:-0.2
- SNOW:-0.5

#感冒为自定义生病效果
#一条效果为 效果名,持续时间,效果等级
#";"可以增加多种效果
# SPEED(速度提升),SLOW(缓慢),FAST_DIGGING（急迫）,SLOW_DIGGING(挖掘疲劳),INCREASE_DAMAGE(伤害提升)
# HEAL(瞬间治疗),HARM(瞬间伤害),JUMP(跳跃提升),CONFUSION(反胃),REGENERATION（生命恢复）
# DAMAGE_RESISTANCE（抗性）,FIRE_RESISTANCE(防火),WATER_BREATHING（水下呼吸）,INVISIBILITY（隐身）
# BLINDNESS(失明)，NIGHT_VISION（夜视）,HUNGER（饥饿），WEAKNESS（虚弱）,POISON（中毒）
# WITHER（凋零）,HEALTH_BOOST（生命提升）,ABSORPTION(伤害吸收),SATURATION(饱和)
##################################################################################################
#注意,ThirstMin(口渴度最小时触发),ThirstMax(口渴度最大值的0.8倍触发),PhysicalStrengthMin(体力最小值触发),SleepMin(睡觉最小值触发),Weight(负重超重时触发),Fever(体温高于38触发),Cold(体温低于36触发),AfterAteWrongMedicine(吃错药后触发),生病(默认生病效果),骨折(骨折时候触发),严重骨折(严重骨折时候触发) 都为内置使用,不能删除整个条目,可以修改具体效果,当想让一条内置条目无效果,直接把":"后面的值全部删掉即可
Effect:
- ThirstMin:WEAKNESS,130,3;WITHER,30,3
- ThirstMax:SATURATION,130,1
- PhysicalStrengthMin:SLOW,130,1;WEAKNESS,130,3
- SleepMin:SLOW,130,1;WEAKNESS,130,3
- SleepMax:SPEED,140,1;DAMAGE_RESISTANCE,130,1
- Weight:SLOW,300,3
- Fever:SLOW,130,1;WEAKNESS,130,3;CONFUSION,130,3
- Cold:SLOW,130,1;WEAKNESS,130,3;CONFUSION,130,3
- AfterAteWrongMedicine:SLOW,130,1;WEAKNESS,130,3;CONFUSION,130,3
- 生病:SLOW,130,1;WEAKNESS,130,3;CONFUSION,130,3
- 骨折:SLOW,250,2;WEAKNESS,250,2;CONFUSION,130,3
- 严重骨折:SLOW,130,1;WEAKNESS,130,3;CONFUSION,130,3
- 感冒:SLOW,130,1;WEAKNESS,130,3;CONFUSION,130,3

#设定属性标签
#如果不满意可以改为其他值,使用效果需要在物品上贴上指定的标签后右击物品使用
#Sleep,Thirst,Medicine,Sickness添加的lore格式如下: 自定义的标签: 10%
#用默认的值举个例子: "睡眠度: +10%" 然后右击这个物品自身的睡眠度就会增加最大值的10%
#MedicineDuration的格式为: 自定义的标签: 10s
#用默认的值举个例子: "药物持续时间: 10s" 右击后获得10s疾病治疗效果
#weight,tem与上面MedicineDuration相似,只不过weigh数值部分不含"s" tem数值部分不是"s"而是"℃"(带不带无所谓啦~~~)
#SickKind,Sick的格式为: 自定义的标签: 疾病名称
#用默认的值举个例子: "专治: 感冒,发烧" 右击后只能治疗"感冒"或者"发烧"这2种病,如果需要治疗更多病可以使用","分格开(只对Sick有效).然而SickKind的值是不支使用","分隔的
#更多信息请看我的帖子
Lore:
- Tem:体温
- Sick:专治
- Weight:负重
- Sleep:睡眠度
- Thirst:口渴度
- Medicine:药物效果
- SickKind:生病种类
- Sickness:生病几率
- PhysicalStrength:体力
- MedicineDuration:药物持续时间

#设定怪物打你时有多少几率生病
#添加格式:
# - 怪物名:病名,几率
#其中如果是默认的怪物名则需要大写,病名必须在Effect下出现过
#如果你的服务器中有改了名的怪物,则可以直接把那个怪物的名字写下来
Mob:
- ZOMBIE:感冒,10%;生病,20%;骨折,5%
- WITHER_SKELETON:感冒,20%
- CREEPER:感冒,10%
- SKELETON:感冒,20%
- SPIDER:感冒,10%
- SLIME:感冒,20%
- ZOMBIE_PIGMAN:感冒,10%
- CAVE_SPIDER:感冒,20%
- WITCH:感冒,10%
- ZOMBIE_VILLAGER:感冒,20%
- ENDERMAN:感冒,10%