language: zh
  
check-update: true
enable-bStats: true
  
mysql:
  enable: false
  host: localhost
  port: 3306
  database: database
  username: root
  password: 123456
 
enable-worlds:
  - world
  - world_nether
  - world_the_end

status-command-cooldown: 600

status:
  sleep:
    enable: true
    sleep-in-day: true
    max: 100
    sub: 0.05
    add: 0.1
    effect-data:
      - "0-25:SPEED,1,1,true;HEAL,1,1,true"
      - "80-100:SPEED,1,1,true;HEAL,1,1,true"
  thirst:
    enable: true
    max: 100
    sub: 0.01
    effect-data:
      - "0-25:SPEED,1,1,true;HEAL,1,1,true"
      - "80-100:SPEED,1,1,true;HEAL,1,1,true"
  energy:
    enable: true
    max: 100
    add: 2
    sneaking: 1
    sprinting: 5
    jumping: 5
    swimming: 3
    effect-data:
      - "0-25:SPEED,1,1,true;HEAL,1,1,true"
      - "80-100:SPEED,1,1,true;HEAL,1,1,true"
    break-block:
      - "SAND,0,1"
  weight:
    enable: true
    max: 100
    effect: "SPEED,1,1,true;HEAL,1,1,true"
    item: 
      - TORCH:0.1
  illness:
    enable: true
  temperature: 
    enable: true

label:
  split: ":"
  labels:
    - "sleep:Sleep"
    - "thirst:Thirst"
    - "weight:Weight"
    - "hunger:Hunger"
    - "energy:Energy"
    - "health:Health"