name: RealSurvival
main: miskyle.realsurvival.RealSurvival
version: 0.4.0
description: Let Minecraft be more real
author: School_Uniform
api-version: 1.13
softdepend: [PlaceholderAPI,Chairs]
commands:
  rsi:
    description: get Realsurvival's help
    usage: /<command> help
  RealSurvival:
    description: get Realsurvival's help
    usage: /<command> help
permissions: 
  RealSurvival.Admin.Item:
    description: Use Admin Commands
    default: op