name: RealSurvival
main: com.outlook.schooluniformsama.RealSurvival
version: 0.3.2
description: Let Minecraft be more real
author: School_Uniform
softdepend: [PlaceholderAPI,Chairs]
commands:
  rs:
    description: get Realsurvival's help
    usage: /<command> help
  RealSurvival:
    description: get Realsurvival's help
    usage: /<command> help
permissions: 
  RealSurvival.Admin:
    description: Use Admin Commands
    default: op