name: RealSurvival
main: miskyle.realsurvival.RealSurvival
version: 0.4.3
description: Let Minecraft be more real
author: miSkYle
api-version: 1.13
softdepend: [PlaceholderAPI,Chairs,Multiverse-Core]
commands:
  RealSurvivalItem:
    description: get RealsurvivalItem's help
    usage: /<command> help
    aliases: [rsi,rsitem,realsurvivali]
  RealSurvival:
    description: get Realsurvival's help
    usage: /<command> help
    aliases: [rs]
  RealSurvivalCube:
    description: get RealSurvivalCube's help
    usage: /<command> help
    aliases: [rsc,rscube,realsurvivalc]
  RealSurvivalRecipe:
    description: get RealSurvivalRecipe's help
    usage: /<command> help
    aliases: [rsr,rsrecipe,realsurvivalr]
permissions: 
  RealSurvival.Admin.Item:
    description: Use RealSurvivalItem Commands
    default: op
  RealSurvival.Recipe.CraftTableRecipeCreate:
    description: Allow Create CraftTable Recipe
    default: op
  RealSurvival.Command.CubeArray:
    description: Allow Create CubeArray
    default: op
  RealSurvival.Player.Admin:
    description: Allow Use Player's Admin Commands
    default: op